version: "3.7"

services:
  app:
    build: .
    image: ymanshur/go-restful:${APP_VERSION}
    container_name: go-restful
    ports:
      - ${APP_PORT}:8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_HOST: host.docker.internal
      DB_NAME: ${DB_NAME}
    restart: always
